### ISSUE TITLE
Model-view-matrix not set

### ISSUE THREAD

**Issue by Magnus2** [sebastianlipponer/glviz#2]
camera.cpp:
The MVM is set only by `set_modelview_matrix_from_orientation()` which is only called in `set_position(.)`, `set_orientation(.)`,`rotate(.)`, and `translate(.)`. If a camera object has just been created and none of these methods have been called, the MVM is not yet set and querying the MVM will return invalid values.
Calling `set_modelview_matrix_from_orientation()` from the Camera constructor fixes this.

**Comment by sebastianlipponer** [comment]
Thanks for pointing this out. The most recent version should fix this.
